### RECIEVER ###

FROM python:3.9
RUN pip install --upgrade pip
RUN pip install requests connexion pykafka connexion[flask] connexion[uvicorn]
WORKDIR /app
# copies all files in the curent directory
COPY . /app 
CMD ["python3", "app.py"]