### STORAGE ###

FROM python
RUN pip install --upgrade pip
RUN pip install connexion sqlalchemy pymysql cryptography pykafka
WORKDIR /app
# copies all files in the curent directory
COPY . /app 
CMD ["python3", "app.py"]